name: CI for Static Website

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Validate HTML & CSS
    runs-on: ubuntu-lastest

    steps:
      - nanme: Checkout code
        uses: actions/checkout@v3

        # Validate HTML
        - name: Validate HTML
          uses: cyb3r-jak3/html5-validator-action@v1.5.0
          with:
            file: "index.html"

          # Validate CSS
          - name: Validate CSS
            uses: dkhunt27/css-validator-github-action@v1
            with:
              css_file: "styles.css"
deploy:
  name: Deploy to GitHub Pages
  needs: validate
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: action/checkout@v3

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload files
      uses: action/upload-pages-artifact@v1
      with:
        path: ./

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
